"""``complexbox.ssdi`` — State-Space Dynamical Independence.

Direct Python port of the SSDI-1 MATLAB toolbox (Barnett, 2023).
"""

from __future__ import annotations

from . import beta_stats, cluster, dd, networks, optimise, transform
from ._grassmann import (
    L2Q,
    Q2L,
    gmetric,
    gmetrics,
    gmetrics1,
    gmetricsx,
    gmetricsxx,
    habeta,
    habetax,
    orthonormalise,
    plucker,
    rand_involution,
    rand_orthonormal,
    subspacea,
    subspaceb,
    subspacec,
)
from ._perfect import dds_check, iss_perfect_dd
from .beta_stats import (
    BetaStatResult,
    HaxaStats,
    get_haxa_cvals,
    habeta_statinf,
    haxa_dist,
    make_haxa_stats,
)
from .cluster import ClusterResult, Lcluster, Lhcluster
from .dd import (
    cak2ddx,
    cak2ddxgrad,
    iss2cak,
    iss2ce,
    iss2ce_precomp,
    iss2dd,
    trfun2dd,
    trfun2dd_band,
    trfun2dd_bandgrad,
    trfun2dd_pointwise,
    trfun2ddgrad,
)
from .networks import tnet9a, tnet9b, tnet9c, tnet9d, tnet243, tneter, tnetmod
from .optimise import (
    GDResult,
    opt_gd1_dds,
    opt_gd1_ddx,
    opt_gd2_dds,
    opt_gd2_ddx,
    opt_gd_dds_mruns,
    opt_gd_ddx_mruns,
)
from .transform import (
    itransform_subspace,
    transform_ss,
    transform_subspace,
    transform_var,
)

__all__ = [
    "dd",
    "optimise",
    "transform",
    "cluster",
    "networks",
    "orthonormalise",
    "rand_orthonormal",
    "rand_involution",
    "subspacea",
    "subspaceb",
    "subspacec",
    "gmetric",
    "gmetrics",
    "gmetrics1",
    "gmetricsx",
    "gmetricsxx",
    "habeta",
    "habetax",
    "plucker",
    "L2Q",
    "Q2L",
    "BetaStatResult",
    "HaxaStats",
    "habeta_statinf",
    "haxa_dist",
    "make_haxa_stats",
    "get_haxa_cvals",
    "beta_stats",
    "iss2cak",
    "cak2ddx",
    "cak2ddxgrad",
    "iss2dd",
    "iss2ce_precomp",
    "iss2ce",
    "trfun2dd",
    "trfun2ddgrad",
    "trfun2dd_pointwise",
    "trfun2dd_band",
    "trfun2dd_bandgrad",
    "transform_ss",
    "transform_var",
    "transform_subspace",
    "itransform_subspace",
    "GDResult",
    "opt_gd1_ddx",
    "opt_gd2_ddx",
    "opt_gd1_dds",
    "opt_gd2_dds",
    "opt_gd_ddx_mruns",
    "opt_gd_dds_mruns",
    "ClusterResult",
    "Lcluster",
    "Lhcluster",
    "iss_perfect_dd",
    "dds_check",
    "tnet9a",
    "tnet9b",
    "tnet9c",
    "tnet9d",
    "tnet243",
    "tneter",
    "tnetmod",
]
