"""``complexbox.mvgc`` — Multivariate Granger causality.

Direct Python port of the MVGC2 MATLAB toolbox (Barnett & Seth, 2014).
"""

from __future__ import annotations

from . import autocov, cpsd, gc, groupwise, mi, modelorder, ss, stats, var
from ._lyap import dlyap, dlyap_aitr, mdare
from ._random import corr_rand, iss_rand, var_rand
from ._specfac import cpsd_specfac
from ._utils import (
    check_group,
    demean,
    is_pos_def,
    logdet,
    maxabs,
    parcov,
    specnorm,
    symmetrise,
    var_decay,
)
from .autocov import autocov_to_cpsd, cpsd_to_autocov, tsdata_to_autocov, tsdata_to_cov
from .cpsd import tsdata_to_cpsd
from .gc import (
    autocov_to_mvgc,
    autocov_to_pwcgc,
    autocov_to_smvgc,
    autocov_to_spwcgc,
    cpsd_to_mvgc,
    cpsd_to_pwcgc,
    cpsd_to_smvgc,
    cpsd_to_spwcgc,
    ss_to_mvgc,
    ss_to_pwcgc,
    ss_to_smvgc,
    ss_to_spwcgc,
    var_to_mvgc,
    var_to_pwcgc,
    var_to_smvgc,
    var_to_spwcgc,
)
from .groupwise import (
    ss_to_cggc,
    ss_to_gwcgc,
    ss_to_gwcggc,
    ss_to_gwiogc,
    ss_to_iogc,
    ss_to_sgwcgc,
    ss_to_sgwiogc,
    ss_to_siogc,
    var_to_cggc,
    var_to_gwcgc,
    var_to_gwcggc,
    var_to_gwiogc,
    var_to_iogc,
    var_to_sgwcgc,
    var_to_sgwiogc,
    var_to_siogc,
)
from .mi import (
    cov_to_cmii,
    cov_to_gwcmi,
    cov_to_gwcmii,
    cov_to_gwiomi,
    cov_to_iomi,
    cov_to_mvmi,
    cov_to_pwcmi,
    cov_to_pwmi,
    cpsd_to_scwiomi,
    cpsd_to_sgwcmi,
    cpsd_to_sgwgmi,
    cpsd_to_sgwiomi,
    cpsd_to_smvmi,
    cpsd_to_spwcmi,
)
from .modelorder import VARModelOrder, tsdata_to_ssmo, tsdata_to_varmo
from .ss import (
    ss2fres,
    ss2itrfun,
    ss2trfun,
    ss_check_fres,
    ss_to_autocov,
    ss_to_cpsd,
    ss_to_tsdata,
    tsdata_to_ss,
)
from .stats import (
    consistency,
    empirical_cdf,
    empirical_cdfi,
    empirical_confint,
    empirical_cval,
    empirical_pval,
    ggc_bias,
    ggc_cdf,
    ggc_cval,
    ggc_icdf,
    ggc_pval,
    infocrit,
    lbqtest,
    lbqtest_cval,
    lbqtest_pval,
    mann_whitney,
    mann_whitney_group,
    mardia,
    mvgc_bias,
    mvgc_cdf,
    mvgc_cval,
    mvgc_icdf,
    mvgc_pval,
    significance,
    tsdata_permute,
    whiteness,
)
from .var import (
    VARFit,
    autocov_to_var,
    tsdata_to_var,
    var2fres,
    var2itrfun,
    var2trfun,
    var_check_fres,
    var_to_autocov,
    var_to_cpsd,
    var_to_ss,
    var_to_tsdata,
)

__all__ = [
    # submodules
    "var",
    "ss",
    "autocov",
    "cpsd",
    "gc",
    "groupwise",
    "mi",
    "stats",
    "modelorder",
    # utils
    "logdet",
    "specnorm",
    "var_decay",
    "demean",
    "symmetrise",
    "maxabs",
    "is_pos_def",
    "parcov",
    "check_group",
    "cpsd_specfac",
    # lyap / DARE
    "dlyap",
    "dlyap_aitr",
    "mdare",
    # random
    "var_rand",
    "corr_rand",
    "iss_rand",
    # VAR
    "VARFit",
    "tsdata_to_var",
    "var_to_tsdata",
    "var_to_ss",
    "var_to_autocov",
    "autocov_to_var",
    "var_to_cpsd",
    "var2trfun",
    "var2itrfun",
    "var_check_fres",
    "var2fres",
    # SS
    "ss_to_autocov",
    "ss_to_cpsd",
    "ss_to_tsdata",
    "ss2trfun",
    "ss2itrfun",
    "ss_check_fres",
    "ss2fres",
    "tsdata_to_ss",
    # autocov / cpsd
    "tsdata_to_autocov",
    "tsdata_to_cov",
    "cpsd_to_autocov",
    "autocov_to_cpsd",
    "tsdata_to_cpsd",
    # GC (var, ss, autocov, cpsd paths)
    "var_to_mvgc",
    "var_to_pwcgc",
    "var_to_smvgc",
    "var_to_spwcgc",
    "ss_to_mvgc",
    "ss_to_pwcgc",
    "ss_to_smvgc",
    "ss_to_spwcgc",
    "autocov_to_mvgc",
    "autocov_to_pwcgc",
    "autocov_to_smvgc",
    "autocov_to_spwcgc",
    "cpsd_to_mvgc",
    "cpsd_to_pwcgc",
    "cpsd_to_smvgc",
    "cpsd_to_spwcgc",
    # Conditional / groupwise / IO GC
    "var_to_iogc",
    "var_to_cggc",
    "var_to_gwcgc",
    "var_to_gwcggc",
    "var_to_gwiogc",
    "ss_to_iogc",
    "ss_to_cggc",
    "ss_to_gwcgc",
    "ss_to_gwcggc",
    "ss_to_gwiogc",
    "var_to_siogc",
    "var_to_sgwcgc",
    "var_to_sgwiogc",
    "ss_to_siogc",
    "ss_to_sgwcgc",
    "ss_to_sgwiogc",
    # MI
    "cov_to_mvmi",
    "cov_to_pwmi",
    "cov_to_cmii",
    "cov_to_pwcmi",
    "cov_to_iomi",
    "cov_to_gwcmi",
    "cov_to_gwcmii",
    "cov_to_gwiomi",
    "cpsd_to_smvmi",
    "cpsd_to_spwcmi",
    "cpsd_to_sgwcmi",
    "cpsd_to_sgwgmi",
    "cpsd_to_sgwiomi",
    "cpsd_to_scwiomi",
    # stats
    "mvgc_cdf",
    "mvgc_icdf",
    "mvgc_pval",
    "mvgc_cval",
    "mvgc_bias",
    "ggc_cdf",
    "ggc_icdf",
    "ggc_pval",
    "ggc_cval",
    "ggc_bias",
    "lbqtest",
    "lbqtest_pval",
    "lbqtest_cval",
    "mardia",
    "mann_whitney",
    "mann_whitney_group",
    "empirical_cdf",
    "empirical_cdfi",
    "empirical_pval",
    "empirical_cval",
    "empirical_confint",
    "tsdata_permute",
    "infocrit",
    "whiteness",
    "consistency",
    "significance",
    # model order
    "VARModelOrder",
    "tsdata_to_varmo",
    "tsdata_to_ssmo",
]
